site_name: Container Doc
pages:
- [index.md, 开发文档]
use_directory_urls: false
copyright: Copyright © 2017 <a href="http://www.bmob.cn/" target="_blank">Bmob</a>, Maintained by the Bmob Support.
site_dir: "../../../../service/container/web"