site_name: 打赏Bmob
pages:
- [index.md, 打赏Bmob]
use_directory_urls: false
copyright: Copyright © 2017 <a href="http://www.bmob.cn/" target="_blank">Bmob</a>, Maintained by the Bmob Support.
site_dir: "../../../../service/other/donate"