site_name: Pay Android
pages:
- [index.md, 开发文档]
- [module/example/README.md, 示例和功能]
#- [module/error_code/README.md, 错误码]
#- [module/common_problem/README.md, 常见问题]
- [module/class_doc/README.md, 类库文档]
- [module/update_log/README.md, 更新日志]
use_directory_urls: false
copyright: Copyright © 2017 <a href="http://www.bmob.cn/" target="_blank">Bmob</a>, Maintained by the Bmob Support.
site_dir: "../../../../service/pay/android"